Create 23editorcs.dat
VISCHub/VSCIRegV1 pull request #13
Opened 2017-10-06 06:14 UTC by 23editorcs

Nguyễn Phú Quý registered to VISC.

2017-10-07 11:07 UTC, vietlq requested changes
You need to hash "VISC:23editorcs" using SHA-256 and KECCAK-256.

2017-10-07 11:07 UTC, vietlq commented on reg/23editorcs.dat
> +SHA-256:(SHA-256(VISC:23editorcs))
Please look at the example for my string `VISC:vietlq`:

```
SHA-256:815f421ea518866d186845a4be3a46828ed21429a896654b36b7ddba1e464d04
KECCAK-256:47620e53f94f7d9f4560e4f89e25bb60513941f39fbc30d2494333431dc6c234
```

You need to hash your string too :)

2017-10-07 11:25 UTC, 23editorcs commented
Yes, I already updated on the last one.

2017-10-07 13:08 UTC, vietlq commented
@23editorcs still isn't right. Show me your code how did you derive the hashes.

2017-10-07 16:47 UTC, 23editorcs commented
I actually used your code to derive the hashes since it printed the output. My code:
python3 verify-sig.py 23editorcs
Is it the right way to do?

2017-10-08 04:12 UTC, 23editorcs commented
@vietlq  Sorry, maybe I typed a wrong string last time. I just updated it again. Please, check it. Thanks

2017-10-10 20:21 UTC, vietlq approved these changes

2017-10-10 20:22 UTC, merged

2017-10-10 20:22 UTC, vietlq commented
@23editorcs thanks for your interest. Please send a request to https://www.facebook.com/groups/VISCHub/ and I will add you :)

2017-10-11 03:51 UTC, 23editorcs commented
Thank for your patience with me :). I have sent the request.